### ISSUE TITLE
Label issue

### ISSUE THREAD

**Issue by duyngha** [vietartisans/cpter#13]

**Comment by sondoha** [comment]
Viet desc nhe Duy de anh em ranh check neu fix duoc se fix luon @duyngha

**Comment by duyngha** [comment]
@sondoha ah no ko phai la bug anh a. Luc chuyen cai CPT UI sang cpter e truyen cai `options` cho cai `labels` sai nen no ko chay. E da cap nhat lai README cho de hieu hon roi.
